MathWars/Models/Answer.cs
using System.ComponentModel.DataAnnotations;

namespace MathWars.Models;

public class Answer
{
    [Key]
    public int Id { get; set; }
    [Required]
    public int UserId { get; set; }
    [Required]
    public int TaskId { get; set; }
    [Required]
    public string Content { get; set; }
    public DateTime SubmissionDate { get; set; }
}

MathWars/Pages/Accounts/ConfirmEmail.cshtml.cs
using MathWars.Entities;
using MathWars.Interfaces;
using MathWars.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace MathWars.Pages.Accounts;

[BindProperties]
public class ConfirmEmailModel : PageModel
{
    private readonly UserManager<ApplicationUser> _userManager;
    private readonly IConfiguration _configuration;
    private readonly IEmailSenderService _emailSenderService;

    public ConfirmEmailModel(UserManager<ApplicationUser> userManager, IConfiguration configuration, IEmailSenderService emailSenderService)
    {
        _userManager = userManager;
        _configuration = configuration;
        _emailSenderService = emailSenderService;
    }

    public string Uid { get; set; }
    public bool IsResendMail { get; set; } = false;

    public async Task<IActionResult> OnGet(string uid)
    {
        var currentUser = await _userManager.GetUserAsync(User);

        if (currentUser != null)
        {
            return RedirectToPage("/Index");
        }

        Uid = uid;
        return Page();
    }

    public async Task<IActionResult> OnPostAsync() 
    {
        var user = await _userManager.FindByIdAsync(Uid);

        if (user != null)
        {
            if(user.EmailConfirmed)
            {
                return RedirectToPage("/Index");
            }

            var token = await _userManager.GenerateEmailConfirmationTokenAsync(user);
            if (!string.IsNullOrEmpty(token))
            {
                await SendEmailConfirmationEmailAsync(user, token);
                IsResendMail = true;
                return Page();
            }
        }

        return Page();
    }
    private async Task SendEmailConfirmationEmailAsync(ApplicationUser user, string token)
    {
        string appDomain = _configuration.GetSection("ApplicationDetails:AppDomain").Value;
        string confirmationLink = _configuration.GetSection("ApplicationDetails:EmailConfirmation").Value;
        UserEmailOptions options = new UserEmailOptions()
        {
            ToEmails = new List<string>() { user.Email },
            PlaceHolders = new List<KeyValuePair<string, string>>
            {
                new KeyValuePair<string, string>("{{UserName}}", user.UserName),
                new KeyValuePair<string, string>("{{Link}}", string.Format(appDomain + confirmationLink,user.Id,token))
            }
        };

        await _emailSenderService.SendEmailForEmailConfirmation(options);
    }

}

MathWars/Pages/Accounts/ConfirmedEmail.cshtml.cs
using MathWars.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MathWars.Pages.Accounts;
public class ConfirmedEmailModel : PageModel
{
    private readonly UserManager<ApplicationUser> _userManager;
    private readonly SignInManager<ApplicationUser> _signInManager;
    public ConfirmedEmailModel(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager)
    {
        _signInManager = signInManager;
        _userManager = userManager;
    }

    public bool Success { get; set; } = false;

    public async Task<IActionResult> OnGet(string uid, string token)
    {
        if(!string.IsNullOrEmpty(uid) && !string.IsNullOrEmpty(token))
        {
            token = token.Replace(" ","+");
            var result = await ConfirmEmailAsync(uid, token);

            if(result.Succeeded)
            {
                var user = await _userManager.FindByIdAsync(uid);
                if (user != null)
                {
                    await _signInManager.SignInAsync(user, isPersistent: false);
                    Success = true;
                    return Page();
                }
            }
        }
        Success = false;

        return Page();
    }

    private async Task<IdentityResult> ConfirmEmailAsync(string uid, string token)
    {
        return await _userManager.ConfirmEmailAsync(await _userManager.FindByIdAsync(uid), token);
    }
}

MathWars/Pages/Accounts/Logout.cshtml.cs
using MathWars.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MathWars.Pages.Accounts
{
    public class LogoutModel : PageModel
    {
        private readonly SignInManager<ApplicationUser> signInManager;

        public LogoutModel(SignInManager<ApplicationUser> signInManager) 
        {
            this.signInManager = signInManager;
        }
        public void OnGet()
        {

        }

        public async Task<IActionResult> OnPostLogoutAsync()
        {
            await signInManager.SignOutAsync();
            return RedirectToPage("/IndexGuest");
        }

        public IActionResult OnPostDontLogoutAsync()
        {
            return RedirectToPage("/Index");
        }
    }
}

MathWars/Pages/Accounts/Profile/AnswerView.cshtml.cs
using MathWars.Entities;
using MathWars.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MathWars.Pages.Accounts.Profile
{
    [Authorize]
    [BindProperties]
    public class AnswerViewModel : PageModel
    {
        private readonly IUnitOfWork _uow;

        public AnswerViewModel(IUnitOfWork uow) 
        {
            _uow = uow;
        }

        public UserAnswer Answer { get; set; }
        public string Uid { get; set; }


        public async Task<IActionResult> OnGetAsync(int id)
        {
            Answer = await _uow.UserAnswersRepository.GetUserAnswersAndTaskAsync(id);

			if (Answer == null)
            {
                return NotFound();
            }

            Uid = Answer.UserId;

            return Page();  
        }
    }
}

MathWars/Pages/Accounts/Profile/IndexProfile.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations;
using MathWars.Helpers;
using MathWars.Entities;
using MathWars.Interfaces;
using MathWars.Models;
using MathWars.Services;

namespace MathWars.Pages
{
    [Authorize]
    [ValidateAntiForgeryToken]
    [BindProperties]
	public class IndexProfileModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly IUnitOfWork _uow;
        private readonly UserManager<ApplicationUser> _userManager;
		private readonly IConfiguration _configuration;
        private readonly IPhotoService _photoService;

        public IndexProfileModel(ILogger<IndexModel> logger, IUnitOfWork uow, 
            UserManager<ApplicationUser> userManager, IConfiguration configuration, 
            IPhotoService photoService)
        {
            _logger = logger;
            _uow = uow;
            _userManager = userManager;
            _configuration = configuration;
            _photoService = photoService;
        }

        public ApplicationUser CurrentUser { get; set; }
		public PaginatedList<UserProfileAnswerModel> AnswersList { get; set; }
        [Required(ErrorMessage = "Jeżeli chcesz zmienić zdjęcie to musisz je dodać"),
            Display(Name = "Dodaj zdjęcie: ")]
        public IFormFile ImageFile { get; set; }
        public string Uid {  get; set; }

        public async Task<IActionResult> OnGet(int? pageIndex, string uid) 
        {
            Uid = uid;
            CurrentUser = await _userManager.FindByIdAsync(uid) ?? new ApplicationUser();

            if (CurrentUser == null) return NotFound();

			int pageSize = _configuration.GetSection("NumberOfElementsInList").GetValue<int>("Profil");

            AnswersList = await _uow.UserAnswersRepository.GetUserProfileAnswersAsync(pageSize, pageIndex, uid);
            return Page();
		}

        public async Task<IActionResult> OnPostUploadImageAsync()
        {
            if (ModelState.IsValid)
            {
                CurrentUser = await _userManager.FindByIdAsync(Uid);

                if (CurrentUser == null) return NotFound();

                var photoResult = await _photoService.AddPhotoAsync(ImageFile, ImageDirectoriesCloudinary.Profiles);

                if (photoResult.Error != null) return Page();

                CurrentUser.ProfileImageUrl = photoResult.SecureUrl.AbsoluteUri;
                CurrentUser.PublicProfileImageId = photoResult.PublicId;

                var result = await _userManager.UpdateAsync(CurrentUser);

                if (result.Succeeded)
                {
                    return RedirectToPage("IndexProfile", new {uid = CurrentUser.Id});
                }
                else
                {
                    return NotFound();
                }
            }

            return RedirectToPage();
        }
    }
}

MathWars/Pages/Accounts/Profile/Leaderboard.cshtml.cs
using MathWars.Entities;
using MathWars.Helpers;
using MathWars.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MathWars.Pages.Accounts.Profile
{
    [Authorize]
    public class LeaderboardModel : PageModel
    {
        private readonly IUnitOfWork _uow;
		private readonly ILogger<IndexModel> _logger;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IConfiguration _configuration;

        public LeaderboardModel(IUnitOfWork uow, ILogger<IndexModel> logger, 
            UserManager<ApplicationUser> userManager, IConfiguration configuration)
        {
            _uow = uow;
            _logger = logger;
            _userManager = userManager;
            _configuration = configuration;
        }

        public PaginatedList<ApplicationUser> Users { get; set; }

        public async Task OnGetAsync(int? pageIndex)
        {
            int pageSize = _configuration.GetSection("NumberOfElementsInList")
                .GetValue<int>("Leaderboard");

            IList<ApplicationUser> usersInRole = await _userManager.GetUsersInRoleAsync("user");

            Users = _uow.UserRepository.GetLeaderboardUsers(usersInRole, pageIndex, pageSize);

        }



    }
}

MathWars/Pages/Accounts/Profile/UserAnswers.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MathWars.Data;
using MathWars.Models;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MathWars.Pages
{
    [Authorize]
    public class UserAnswersModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly ApplicationDbContext _db;
        private readonly UserManager<ApplicationUser> _userManager;
		[BindProperty]
		public ApplicationUser currentUser { get; set; }
		[BindProperty]
		public IEnumerable<Answers> answers { get; set; }

        public UserAnswersModel(ApplicationDbContext db, ILogger<IndexModel> logger, UserManager<ApplicationUser> userManager)
        {
            _db = db;
            _logger = logger;
            _userManager = userManager;
        }

        public async Task OnGet()
        {
            currentUser = await _userManager.GetUserAsync(User);
			answers = _db.Answers.Include(a => a.Task).Where(a => a.UserId == currentUser.Id).ToList();
		}
    }
}

MathWars/Pages/Accounts/Roles/CreateRole.cshtml.cs
using MathWars.Data;
using MathWars.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;

namespace MathWars.Pages.TaskPages;
[Authorize(Policy = "RequireAdminRole")]
[BindProperties]
public class CreateRoleModel : PageModel
{
    private readonly RoleManager<IdentityRole> _roleManager;
    public IdentityRole role { get; set; }
    public CreateRoleModel(RoleManager<IdentityRole> roleManager)
    {
        _roleManager = roleManager;
    }
    public void OnGet()
    {
    }

    public async Task<IActionResult> OnPost()
    {
        if (ModelState.IsValid)
        {
            var result =  await _roleManager.CreateAsync(role);
            if (result.Succeeded)
            {
                return RedirectToPage("ViewRole");
            }
            foreach (IdentityError error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }
        }
        return Page();
    }
}

MathWars/Pages/Accounts/Roles/DeleteRole.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MathWars.Pages.TaskPages;
[Authorize(Policy = "RequireAdminRole")]
[BindProperties]
public class DeleteRoleModel : PageModel
{
    private readonly RoleManager<IdentityRole> _roleManager;
    public IdentityRole role { get; set; }

    public DeleteRoleModel(RoleManager<IdentityRole> roleManager)
    {
        _roleManager = roleManager;
    }
    public async void OnGet(string id)
    {
        role = await _roleManager.FindByIdAsync(id);
    }

    public async Task<IActionResult> OnPost()
    {
        var roleToDelete = await _roleManager.FindByIdAsync(role.Id);

        if (roleToDelete != null)
        {
            var bannedToDeleteList = new List<string> { "admin", "taskManager", "user" };

            foreach (var banned in bannedToDeleteList)
            {
                if (roleToDelete.Name == banned)
                {
                    ModelState.AddModelError("", "You can't delete this role");
                    return Page();
                }
            }

            var result = await _roleManager.DeleteAsync(roleToDelete);

            if (result.Succeeded)
            {
                return RedirectToPage("ViewRole");
            }
            foreach (IdentityError error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }
        }
        return Page();

    }
}

MathWars/Pages/Accounts/Roles/EditRole.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MathWars.Pages.TaskPages;
[Authorize(Policy = "RequireAdminRole")]
[BindProperties]
public class EditRoleModel : PageModel
{
    private readonly RoleManager<IdentityRole> _roleManager;
    public IdentityRole role { get; set; }

    public EditRoleModel(RoleManager<IdentityRole> roleManager)
    {
        _roleManager = roleManager;
    }
    public async void OnGet(string id)
    {
        role = await _roleManager.FindByIdAsync(id);
    }

    public async Task<IActionResult> OnPost()
    {
        var roleToUpdate = await _roleManager.FindByIdAsync(role.Id);

        if (roleToUpdate != null)
        {
            var bannedToUpdateList = new List<string> { "admin", "taskManager", "user" };

            foreach (var banned in bannedToUpdateList)
            {
                if (roleToUpdate.Name == banned)
                {
                    ModelState.AddModelError("", "You can't update this role");
                    return Page();
                }
            }
            roleToUpdate.Name = role.Name;

            var result = await _roleManager.UpdateAsync(roleToUpdate);

            if (result.Succeeded)
            {
                return RedirectToPage("ViewRole");
            }
            foreach (IdentityError error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }
        }
        return Page();
    }
}

MathWars/Pages/Accounts/Roles/ViewRole.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MathWars.Data;
using MathWars.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Configuration;
using MathWars.Helpers;

namespace MathWars.Pages.TaskPages;
[Authorize(Policy = "RequireAdminOrManagerRole")]
public class ViewRoleModel : PageModel
{
    private readonly RoleManager<IdentityRole> _roleManager;
	private readonly IConfiguration _configuration;

	public ViewRoleModel(RoleManager<IdentityRole> roleManager, IConfiguration configuration)
	{
		_roleManager = roleManager;
		_configuration = configuration;
	}

	public PaginatedList<IdentityRole> Roles { get; set; }

	public async Task OnGetAsync(int? pageIndex)
	{
		int pageSize = _configuration.GetSection("NumberOfElementsInList").GetValue<int>("Roles");
		IQueryable<IdentityRole> roleQuery = _roleManager.Roles;

		Roles = await PaginatedList<IdentityRole>.CreateAsync(roleQuery, pageIndex ?? 1, pageSize);
	}
}

MathWars/Pages/Accounts/Profile/AnswerView.cshtml
@page
@model MathWars.Pages.Accounts.Profile.AnswerViewModel
@{
}

<div class="container">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary pl-3">Twoje rozwiązane zadanie</h2>
            <hr />
        </div>
        <div class="mb-3">
            <h5><label asp-for="@Model.Answer.Task.Content">Treść</label></h5>
            <textarea asp-for="@Model.Answer.Task.Content" class="form-control" readonly></textarea>
        </div>
        <div class="mb-3">
            <h5><label>Zdjęcie tablicy</label></h5>
            <div>
                <img width="50%" src="~/images/WhiteBoardImage/YouCanDeleteMe.png" alt="Report Image" class="task-image" />
            </div>
        </div>
        @* <div class="mb-3">
            <h5><label asp-for="@Model.Answer.Answer">Poprawna odpowiedź</label></h5>
            <input asp-for="@Model.Answer.Answer" class="form-control" readonly/>
        </div> *@
        <a asp-page="IndexProfile" asp-route-uid="@Model.Uid" class="btn btn-secondary" style="width:150px;">Powrót do profilu</a>
    </div>
</div>

MathWars/Pages/Accounts/Profile/ChangePassword.cshtml
@page
@model MathWars.Pages.Accounts.Profile.ChangePasswordModel
@{
}


<div class="container">
    <form method="post">
        <div class="border p-3 mt-4">

            <div class="row pb-2">
                <h2 class="text-primary pl-3">Zmień hasło</h2>
                <hr />
            </div>
            <div asp-validation-summary="All"></div>

            <input asp-for="@Model.Uid" hidden/>
            <div class="mb-3">
                <label asp-for="@Model.CurrentPassword"></label>
                <input asp-for="@Model.CurrentPassword" class="form-control" />
                
            </div>

            <div class="mb-3">
                <label asp-for="@Model.NewPassword"></label>
                <input asp-for="@Model.NewPassword" class="form-control" />
                
            </div>

            <div class="mb-3">
                <label asp-for="@Model.ConfirmPassword"></label>
                <input asp-for="@Model.ConfirmPassword" class="form-control" />
                
            </div>

            <button type="submit" class="btn btn-primary" style="width:150px;">Potwierdź</button>
            <a asp-page="IndexProfile" asp-route-uid="@Model.Uid" class="btn btn-secondary" style="width:150px;">Powrót</a>
        </div>
    </form>
</div>

MathWars/Pages/Accounts/Profile/IndexProfile.cshtml
@page
@using System.Security.Claims

@model IndexProfileModel
@{
}

<link rel="stylesheet" href="~/css/UserProfile.css" asp-append-version="true" />

<div class="container p-3">

    <!-- Section for Level and Experience -->
    <div class="row pt-4">

        <div class="col-4">
            <div class="bg-light" style="padding: 20px;height: 360px; align-items: center;">
                <div class="image-container" data-toggle="modal" data-target="#aModal">
                    <img width="100%" src="@Url.Content(Model.CurrentUser.ProfileImageUrl)" alt="Profile Image" class="task-image" />
                    <i class="fas fa-edit edit-icon" data-toggle="modal" data-target="#aModal"></i>
                </div>
            </div>
        </div>

        <div class="col-4">
            <div class="bg-light" style="padding: 20px;height: 360px; align-items: center;">
                <h2 class="text-primary">Twoje dane:</h2>
                <div style="margin: 40px;">
                    <h5>Nazwa użytkownika:</h5>
                    <p>@User.Identity.Name</p>
                    <h5>E-mail:</h5>
                    <p>@User.FindFirstValue(ClaimTypes.Email)</p>
                </div>
                <a asp-page="ChangePassword" asp-route-uid="@Model.Uid" class="btn btn-primary mx-2">
                    Chcesz zmienić swoje hasło?
                </a>
            </div>
        </div>

        <div class="col-4">
            <div class="bg-light" style="padding: 20px; height: 180px; align-items: center;">
                <h2 class="text-primary">Twój poziom</h2>
                <h1 class="text-primary">@Model.CurrentUser.Level</h1>
            </div>
            <div class="bg-light" style=" padding: 20px; height: 180px;">
                <h2 class="text-primary">Doświadczenie</h2>
                <h3 class="text-primary">@Model.CurrentUser.Experience / @Model.CurrentUser.ExpToReachNewLvl</h3>
                <div class="progress">
                    <div class="progress-bar" role="progressbar" style="width: @(Model.CurrentUser.Experience * 100 / Model.CurrentUser.ExpToReachNewLvl)%;" aria-valuenow="@Model.CurrentUser.Experience" aria-valuemin="0" aria-valuemax="@Model.CurrentUser.ExpToReachNewLvl"></div>
                </div>
            </div>
        </div>

    </div>

    <!--Pop up menu to edit profile picture-->
    @*modal*@
    <div class="modal fade" id="aModal" tabindex="-1" role="dialog" aria-labelledby="aModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="aModalLabel">Zmień swoje zdjęcie profilowe</h4>
                </div>
                <div class="modal-body">
                    <form method="post" enctype="multipart/form-data" asp-page-handler="UploadImage">
                        <div class="form-group">
                            <input asp-for="Uid" hidden />
                            <label asp-for="ImageFile"></label>
                            <input type="file" accept="image/*" asp-for="@Model.ImageFile" class="form-control" />
                            <span asp-validation-for="ImageFile" class="text-danger" hidden></span>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Upload" class="btn btn-primary" />
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Section for Answers -->
    <div class="row pt-4">
        <div class="col-12">
            <div class="bg-light" style="padding: 20px;">
                <h2 class="text-primary">Twoje odpowiedzi</h2>
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Treść</th>
                            <th>Poziom trudności</th>
                            <th>Data ukończenia</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var obj in Model.AnswersList)
                        {
                            <tr>
                                <td width="35%" style="overflow-wrap: break-word; word-break: break-all;">@obj.Content</td>
                                <td width="10%">@obj.DifficultyLevel</td>
                                <td width="20%">@obj.SubmissionDate</td>
                                <td width="10%">
                                    <div>
                                        <a asp-page="AnswerView" asp-route-id="@obj.Id" class="btn btn-primary mx-2">
                                            <i class="bi bi-three-dots"></i>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>

                <!-- Pagination -->
                @if (Model.AnswersList.HasPreviousPage || Model.AnswersList.HasNextPage)
                {
                    <nav aria-label="Page navigation">
                        <ul class="pagination justify-content-center">
                            @if (Model.AnswersList.HasPreviousPage)
                            {
                                <li class="page-item">
                                    <a class="page-link" asp-page="./IndexProfile" asp-route-uid="@Model.Uid" asp-route-pageIndex="@(Model.AnswersList.PageIndex - 1)"><i class="bi bi-arrow-left"></i></a>
                                </li>
                            }

                            @for (var i = Model.AnswersList.PageIndex - 4; i <= Model.AnswersList.PageIndex + 4; i++)
                            {
                                if (i >= 1 && i <= Model.AnswersList.TotalPages)
                                {
                                    <li class="page-item @(i == Model.AnswersList.PageIndex ? "active" : "")">
                                        <a class="page-link" asp-page="./IndexProfile" asp-route-uid="@Model.Uid" asp-route-pageIndex="@i">@i</a>
                                    </li>
                                }
                            }

                            @if (Model.AnswersList.HasNextPage)
                            {
                                <li class="page-item">
                                    <a class="page-link" asp-page="./IndexProfile" asp-route-uid="@Model.Uid" asp-route-pageIndex="@(Model.AnswersList.PageIndex + 1)"><i class="bi bi-arrow-right"></i></a>
                                </li>
                            }
                        </ul>
                    </nav>
                }

            </div>
        </div>
    </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.20.0/jquery.validate.min.js"></script>
<script src="~/js/UserProfile.js"></script>

MathWars/Pages/Accounts/Profile/Leaderboard.cshtml
@page
@model MathWars.Pages.Accounts.Profile.LeaderboardModel
@{
}

<link rel="stylesheet" href="~/css/Leaderboard.css" asp-append-version="true" />

<div class="container p-3">
	<div class="row pt-4">
		<div class="col-6">
			<h2 class="text-primary">Tabela wyników</h2>
		</div>
	</div>

	<br /><br />

	<table class="table table-bordered table-striped" style="width:100%">
		<thead>
			<tr>
				<th>
					Pozycja
				</th>
				<th>
					Użytkownik
				</th>
				<th>
					Poziom
				</th>
				<th>
					Doświadczenie
				</th>
			</tr>
		</thead>
		<tbody>
			@if (Model.Users != null)
			{
				int i = ((Model.Users.PageIndex - 1) * Model.Users.PageSize) + 1;
				@foreach (var obj in Model.Users)
				{
					<tr>
						<td width="10%">#@i</td>
						<td width="30%">
							@if (i == 1)
							{
								<i class="bi bi-trophy-fill gold-icon"></i> 
							}
							else if (i == 2)
							{
								<i class="bi bi-trophy silver-icon"></i> 
							}
							else if (i == 3)
							{
								<i class="bi bi-trophy bronze-icon"></i> 
							}
							@obj.UserName
						</td>
						<td width="30%">@obj.Level</td>
						<td width="30%">@obj.Experience</td>
					</tr>
					i++;
				}
			}
		</tbody>
	</table>

	<!-- Pagination -->
	@if (Model.Users.HasPreviousPage || Model.Users.HasNextPage)
	{
		<nav aria-label="Page navigation">
			<ul class="pagination justify-content-center">
				@if (Model.Users.HasPreviousPage)
				{
					<li class="page-item">
						<a class="page-link" asp-page="./Leaderboard" asp-route-pageIndex="@(Model.Users.PageIndex - 1)"><i class="bi bi-arrow-left"></i></a>
					</li>
				}

				@for (var i = Model.Users.PageIndex - 4; i <= Model.Users.PageIndex + 4; i++)
				{
					if (i >= 1 && i <= Model.Users.TotalPages)
					{
						<li class="page-item @(i == Model.Users.PageIndex ? "active" : "")">
							<a class="page-link" asp-page="./Leaderboard" asp-route-pageIndex="@i">@i</a>
						</li>
					}
				}

				@if (Model.Users.HasNextPage)
				{
					<li class="page-item">
						<a class="page-link" asp-page="./Leaderboard" asp-route-pageIndex="@(Model.Users.PageIndex + 1)"><i class="bi bi-arrow-right"></i></a>
					</li>
				}
			</ul>
		</nav>
	}

</div>