MathWars/Pages/TaskPages/Category/ViewTasksCategory.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Authorization;
using MathWars.Helpers;
using MathWars.Entities;
using MathWars.Interfaces;
using MathWars.Models;

namespace MathWars.Pages.TaskPages.Category
{
	[Authorize(Policy = "RequireAdminOrManagerRole")]
	[BindProperties]
	public class ViewTasksCategoryModel : PageModel
	{
		private readonly IUnitOfWork _uow;
		private readonly IConfiguration _configuration;
		private readonly ILogger<ViewTasksCategoryModel> _logger;
		public ViewTasksCategoryModel(IUnitOfWork uow, IConfiguration configuration, ILogger<ViewTasksCategoryModel> logger)
		{
			_uow = uow;
			_configuration = configuration;
			_logger = logger;
		}

		public TaskCategoryModel Category { get; set; }
		public PaginatedList<TasksCategory> Categories { get; set; }

		public async Task OnGetAsync(int? pageIndex)
		{
			int pageSize = _configuration.GetSection("NumberOfElementsInList")
				.GetValue<int>("Categories");

			IQueryable<TasksCategory> categoryQuery = _uow.TaskCategoryRepository
				.GetTaskCategoriesQueryable();

			Categories = await PaginatedList<TasksCategory>
				.CreateAsync(categoryQuery, pageIndex ?? 1, pageSize);
		}

		public async Task<IActionResult> OnPostCreateCategory()
		{
			if (ModelState.IsValid)
			{
				var ct = new TasksCategory
				{
					CategoryName = Category.CategoryName
				};

				await _uow.TaskCategoryRepository.CreateTaskCategoryAsync(ct);

				if (await _uow.Complete()) return RedirectToPage("ViewTasksCategory");

				_logger.LogError("Problem after saving new task category");

				return BadRequest();
			}
			return RedirectToPage();
		}

		public async Task<IActionResult> OnPostEditCategory(int id, string newName)
		{
			var category = await _uow.TaskCategoryRepository.FindTaskCategoryByIdAsync(id);

			if (category == null)
			{
				_logger.LogError("Can't find category by given id");
				return NotFound();
			}

			category.CategoryName = newName;

			_uow.TaskCategoryRepository.UpdateCategoryNameAsync(category);

			if (await _uow.Complete()) return RedirectToPage();

			_logger.LogError("Problem with saving data about updated category");
			return BadRequest();
		}

		public async Task<IActionResult> OnPostDeleteTaskCategory(int id)
		{
			var category = await _uow.TaskCategoryRepository.FindTaskCategoryByIdAsync(id);

			if (category == null) {
				_logger.LogError("Can't find category by given id");
				return NotFound(); 
			}

			_uow.TaskCategoryRepository.DeleteTaskCategory(category);

			if(await _uow.Complete()) return RedirectToPage();

			_logger.LogError("Problem with saving data about deleted category");
			return BadRequest();
		}
	}

}

MathWars/Pages/TaskPages/DeleteTask.cshtml.cs
using MathWars.Entities;
using MathWars.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MathWars.Pages.TaskPages;

[Authorize(Policy = "RequireAdminOrManagerRole")]
[BindProperties]
public class DeleteTaskModel : PageModel
{
    private readonly IPhotoService _photoService;
    private readonly IUnitOfWork _uow;

    public DeleteTaskModel(IUnitOfWork uow, IPhotoService photoService)
    {
        _uow = uow;
        _photoService = photoService;
    }

    public Tasks Task {  get; set; }

    public async Task<IActionResult> OnGet(int id)
    {
        Task = await _uow.TaskRepository
            .GetTaskWithCategoriesByIdAsync(id);

        if (Task == null)
        {
            return NotFound();
        }

        return Page();
    }

    public async Task<IActionResult> OnPost()
    {
        if (Task.Id > 0)
        {
            var taskFromDb = await _uow.TaskRepository
                .GetTaskWithCategoriesAndAnswersByIdAsync(Task.Id);

            if (taskFromDb != null)
            {
                _uow.TaskRepository.DelateRelationWithAnswers(taskFromDb);

                _uow.TaskRepository.DelateRelationWithCategories(taskFromDb);

                if (!string.IsNullOrEmpty(taskFromDb.PublicImageId))
                {
                    await _photoService.DeletePhotoAsync(taskFromDb.PublicImageId);
                }
                _uow.TaskRepository.DeleteTask(taskFromDb);

                if(await _uow.Complete()) return RedirectToPage("ViewTasks");
                return Page();
            }
            return Page();
        }
        return NotFound();
    }
}

MathWars/Pages/TaskPages/ViewTasks.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using MathWars.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using MathWars.Helpers;
using MathWars.Entities;

namespace MathWars.Pages.TaskPages
{
    [Authorize(Policy = "RequireAdminOrManagerRole")]
    public class ViewTasksModel : PageModel
	{
		private readonly ApplicationDbContext _db;
		private readonly IConfiguration _configuration;
		public ViewTasksModel(ApplicationDbContext db, IConfiguration configuration)
		{
			_db = db;
			_configuration = configuration;
		}

		public PaginatedList<Tasks> Tasks { get; set; }

		public async Task OnGetAsync(int? pageIndex)
		{
			int pageSize = _configuration.GetSection("NumberOfElementsInList").GetValue<int>("Task");
			IQueryable<Tasks> tasksQuery = _db.Tasks
				.Include(t => t.TasksAndCategories)
					.ThenInclude(tc => tc.TaskCategory)
				//.Include(a => a.AnswerType)
				.OrderByDescending(t => t.Created);

			Tasks = await PaginatedList<Tasks>.CreateAsync(tasksQuery, pageIndex ?? 1, pageSize);
		}
	}
}

MathWars/Pages/TaskPages/addTasks.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MathWars.Data;
using MathWars.Models;

namespace MathWars.Pages.TaskPages;

public class addTasksModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;
    private readonly ApplicationDbContext _db;
    public IEnumerable<Tasks> Tasks { get; set; }

    public addTasksModel(ApplicationDbContext db, ILogger<IndexModel> logger)
    {
        _db = db;
        _logger = logger;
    }

    public void OnGet()
    {
        Tasks = _db.Tasks;
    }
}

MathWars/Pages/TaskPages/EditTask/Start.cshtml
@page
@model MathWars.Pages.TaskPages.EditTask.StartModel
@{
}
<link rel="stylesheet" href="~/css/TaskStepper.css">


<div class="container p-3">
    <div class="steps">
        <div class="step @(Model.Step == 1 ? "active" : "")">kategorie</div>
        <div class="step @(Model.Step == 2 ? "active" : "")">treść</div>
        <div class="step @(Model.Step == 3 ? "active" : "")">zdjęcie</div>
        <div class="step @(Model.Step == 4 ? "active" : "")">odpowiedzi</div>
        <div class="line"></div>
    </div>
</div>

<div class="container border p-3 mt-4" style="color: black;">
    @{
        switch (Model.Step)
        {
            case 1:
                await Html.RenderPartialAsync("Step1", Model.CategoriesAndCategory);
                break;
            case 2:
                await Html.RenderPartialAsync("Step2", Model.TaskContent);
                break;
            case 3:
                await Html.RenderPartialAsync("Step3", Model.TaskImage);
                break;
            case 4:
                await Html.RenderPartialAsync("Step4", Model.TaskAnswersAndDifficulty);
                break;
        }
    }
</div>

MathWars/Pages/TaskPages/EditTask/Step1.cshtml
@model MathWars.Models.CategoriesListAndCategoryModel

<div class="container">
	<div class="row pt-4">
		<div class="col-6">
			<h2 class="text-primary">Wybierz kategorię</h2>
		</div>
		<div class="col-6 text-end">
			<a data-toggle="modal" data-target="#CreateTaskCategory" class="btn btn-primary">
				<i class="bi bi-plus-square"></i> &nbsp;Stwórz nową kategorie
			</a>
			<a asp-page="/TaskPages/Category/ViewTasksCategory" class="btn btn-primary">
				<i class="bi bi-plus-square"></i> &nbsp;Edytuj kategorie
			</a>
		</div>
	</div>

	<!--Pop up menu to create new category-->
	@*modal*@
	<div class="modal fade" id="CreateTaskCategory" tabindex="-1" role="dialog" aria-labelledby="aModalLabel" aria-hidden="true">
		<div class="modal-dialog" role="document">
			<div class="modal-content" style="color: black;">
				<div class="modal-header">
					<h4 class="modal-title" id="aModalLabel">Stwórz kategorie zadań</h4>
				</div>
				<form method="post" asp-page-handler="CreateCategory">
					<div class="modal-body">
						<div class="border p-3 mt-4">
							<div class="mb-3">
								Nazwa:
								<input asp-for="@Model.Category.CategoryName" class="form-control" />
								<span asp-validation-for="@Model.Category.CategoryName" class="text-danger"></span>
							</div>
						</div>
					</div>
					<div class="modal-footer">
						<button type="submit" class="btn btn-primary" style="width:150px;">Stwórz</button>
						<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
					</div>
				</form>
			</div>
		</div>
	</div>


	<br /><br />
	<form method="post">
		<table class="table table-bordered table-striped" style="width:100%">
			<thead>
				<tr>
					<th>
						Nazwa
					</th>
					<th>
						Data utworzenia
					</th>
					<th>
						Zaznacz wybrane
					</th>
				</tr>
			</thead>
			<tbody>
				@foreach (var obj in Model.Categories)
				{
					<tr>
						<td width="20%">@obj.CategoryName</td>
						<td width="20%">@obj.Created</td>
						<td>
							@{
								var isChecked = Model.SelectedCategoryIds.Any(tc => tc == obj.Id);
								<div class="form-check">
									<input type="checkbox" value="@obj.Id" name="SelectedCategoryIds" class="form-check-input" @(isChecked ? "checked" : "") />
								</div>
							}
						</td>
					</tr>	
				}
			</tbody>
		</table>

		<input asp-for="CurrentPageIndex" value="@Model.Categories.PageIndex" hidden/>

		<!-- Pagination -->
		@if (Model.Categories.HasPreviousPage || Model.Categories.HasNextPage)
		{
			<nav aria-label="Page navigation">
				<ul class="pagination justify-content-center">
					@if (Model.Categories.HasPreviousPage)
					{
						<li class="page-item">
							<button class="page-link" type="submit" asp-page-handler="CategoriesList" asp-route-pageIndex="@(Model.Categories.PageIndex - 1)"><i class="bi bi-arrow-left"></i></button>
						</li>
					}

					@for (var i = Model.Categories.PageIndex - 4; i <= Model.Categories.PageIndex + 4; i++)
					{
						if (i >= 1 && i <= Model.Categories.TotalPages)
						{
							<li class="page-item @(i == Model.Categories.PageIndex ? "active" : "")">
								<button class="page-link" type="submit" asp-page-handler="CategoriesList" asp-route-pageIndex="@i">@i</button>
							</li>
						}
					}

					@if (Model.Categories.HasNextPage)
					{
						<li class="page-item">
							<button class="page-link" type="submit" asp-page-handler="CategoriesList" asp-route-pageIndex="@(Model.Categories.PageIndex + 1)"><i class="bi bi-arrow-right"></i></button>
						</li>
					}
				</ul>
			</nav>
		}
		<div style="margin: 10px">
			<span asp-validation-for="SelectedCategoryIds" class="text-danger"></span>
		</div>
		
		<a asp-page="/TaskPages/ViewTasks" class="btn btn-primary">Powrót</a>
		<button asp-page-handler="Step1" type="submit" class="btn btn-primary">Następny</button>

	</form>
</div>

MathWars/Pages/TaskPages/EditTask/Step2.cshtml
@model MathWars.Models.TaskContentModel

<div class="container">
    <form method="post">
        <div>
            <div class="row pb-2">
                <h2 class="text-primary pl-3">Treść zadania</h2>
           
            </div>
            <div class="mb-3">
                <div style="overflow-wrap: break-word; word-break: break-all; maxlength=" 30"" id="latex-preview"></div>
                <textarea id="latex-preview-input" asp-for="Content" class="form-control" rows="4"></textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
                <button type="button" class="btn btn-secondary" onclick="addEquations()">Dodaj układ równań</button>
            </div>
            <div class="mb-3">
                <h4>Kreator równań:</h4>
                <div class="mb-3 m-lg-3">
                    Treść LaTeX (treść gotowa do skopiowania):
                    <button type="button" class="btn btn-secondary" id="copy-button">Kopiuj</button>
                    <textarea class="form-control" id="latex-input" disabled></textarea>
                    <div class="mb-3 m-md-1">
                        <h6>Edytor (Jeżeli wklejasz to bez znaków zewnętrznych):</h6>
                        <div id="mathquill-editor"></div>
                    </div>
                </div>

                <table class="math-keyboard">
                    <tr>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('x')">\(x\)</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\alpha')">α</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\lambda')">λ</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\pi')">\(\pi\)</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\Delta')">\(\Delta\)</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\frac{}{}')">\(\frac{x}{y}\)</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\_{}')">\(x_{y}\)</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\sqrt{}')">\(\sqrt{x}\)</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\bigcap')">\( \bigcap \)</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\bigcup')">\( \bigcup \)</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\bigsqcup')">\( \sqcup \)</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\bigsqcap')">\( \sqcap \)</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\implies')">\( \implies \)</button></td>
                    </tr>
                    <tr>
                        
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('y')">\(y\)</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\beta')">β</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\omega')">ω</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\Omega')">\(\Omega\)</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\degree')">\( \degree \)</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\overline{}')">\(\overline{x}\)</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\_{}^{}')">\(x_y^z\)</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\sqrt[{}]{}')">\( \sqrt[x]{y} \)</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\downarrow')">\( \downarrow \)</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\Downarrow')">\( \Downarrow \)</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\uparrow')">\( \uparrow \)</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\Uparrow')">\( \Uparrow \)</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\iff')">\( \iff \)</button></td>
                        
                    </tr>
                    <tr>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('z')">\(z\)</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\delta')">δ</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\prod')">\(\prod\)</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\partial')">\( \partial \)</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\div')">\( \div \)</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\cdot')">\(\cdot\)</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\^{}')">\(y^{x}\)</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\gets')">\( \gets \)</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\forall')">\( \forall \)</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\exist')">\( \exist \)</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\bigvee')">\( \bigvee \)</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\bigwedge')">\( \bigwedge \)</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\impliedby')">\( \impliedby \)</button></td>
                    </tr>
                    <tr>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\gamma')">γ</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\theta')">θ</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\sum')">\(\sum\)</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\int')">\(\int\)</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\ne')">\(\ne\)</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\simeq')">≃</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\infin')">\( \infin \)</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\to')">\( \to \)</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\sqsubset')">⊏</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\sqsupset')">⊐</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\sqsubseteq')">⊑</button></td>
                        <td><button type="button" class="btn btn-secondary" onclick="insertSymbol('\\sqsupseteq')">⊒</button></td>
                        <td>
                            <button type="button" class="btn btn-secondary" onclick="insertSymbol('\\circ')">\( \circ \)</button>
                            <button type="button" class="btn btn-secondary" onclick="insertSymbol('\\bull')">\( \bull \)</button>
                        </td>
                        
                        
                        
                    </tr>
                </table>
            </div>

            <button class="btn btn-primary" type="submit" asp-route-step="1">Poprzedni</button>
            <button asp-page-handler="Step2" class="btn btn-primary" type="submit">Następny</button>
            
        </div>
    </form>
</div>

<script src="~/lib/mathquill-0.10.1/mathquill.js"></script>
<script src="~/js/MathEditor.js"></script>
<script src="~/js/RenderMathInTaskContent.js"></script>

MathWars/Pages/TaskPages/EditTask/Step3.cshtml
@model MathWars.Models.TaskImageModel

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.9.3/dropzone.min.css" />

<form method="post" enctype="multipart/form-data">
    <div class="mb-3">
        <h2 class="text-primary pl-3">Możesz dodać zdjęcie</h2>
        <div action="~/images/forTasks" id="my-dropzone" class="dropzone">
            <input type="file" accept="image/*" asp-for="@Model.Image" />
            <span asp-validation-for="@Model.Image" class="text-danger"></span>
        </div>
        @if (!string.IsNullOrEmpty(@Model.ImagePath))
        {
            <h4>Aktualnie dodany</h4>
            <img id="uploadedImage" src="@Url.Content(Model.ImagePath)" alt="Uploaded Image" style="max-width: 100%; max-height: 200px;" />
        }
    </div>

    <button class="btn btn-primary" type="submit" asp-route-step="2">Poprzedni</button>
    <button asp-page-handler="Step3" class="btn btn-primary" type="submit">Następny</button>
</form>

<script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.9.3/min/dropzone.min.js"></script>

<script>
    document.querySelector('input[type=file]').addEventListener('change', function (event) {
        var reader = new FileReader();
        reader.onload = function () {
            var img = document.createElement('img');
            img.src = reader.result;
            document.body.appendChild(img);
        };
        reader.readAsDataURL(event.target.files[0]);
    });
    Dropzone.options.myDropzone = {
        acceptedFiles: 'image/*',
        maxFiles: 1,
        maxFilesize: 20,
        dictDefaultMessage: 'Upuść tutaj zdjęcia, aby je przesłać',
        dictFallbackMessage: "Your browser does not support drag & drop feature.",
        dictInvalidFileType: "Your uploaded file type is not supported.",
        dictFileTooBig: "File is too big ({{filesize}} MB). Max filesize: {{maxFilesize}} MB.",
        dictResponseError: "Server responded with {{statusCode}} code.",
        dictCancelUpload: "Cancel Upload",
        dictRemoveFile: "Remove",
        init: function () {
            this.on("complete", function (file) {
                this.removeFile(file);
            });
        }
    };
</script>

MathWars/Pages/TaskPages/EditTask/Step4.cshtml
@model MathWars.Models.TaskAnswersAndDifficulty

<form method="post">
    <div class="mb-3">
        <h2 class="text-primary pl-3">Poziom trudności</h2>
        <div class="range">
            <div class="range-slider">
                <input asp-for="@Model.DifficultyLevel"
                       type="range"
                       min="1"
                       max="6"
                       value="@Model.DifficultyLevel"
                       id="range"
                       step="1" />
                <div class="sliderticks">
                    <span>1</span>
                    <span>2</span>
                    <span>3</span>
                    <span>4</span>
                    <span>5</span>
                    <span>6</span>
                </div>
            </div>
        </div>
        <span asp-validation-for="@Model.DifficultyLevel" class="text-danger"></span>
    </div>


    <div class="mb-3">
        <h2 class="text-primary pl-3">Wprowadź odpowiedzi do zadania i zaznacz poprawne</h2>


        <h4>Wybierz ilość odpowiedzi: <input type="number" min="2" max="8" asp-for="@Model.NumberOfAnswers" />
            <button asp-page-handler="SetNumberOfAnswers" type="submit">Potwierdź</button>
        </h4>

        @{
            int numberOfCharInASCII = 65;
            for (int i = 0; i < Model.NumberOfAnswers; i++)
            {
                char letter = Convert.ToChar(numberOfCharInASCII);

                var isChecked = Model.CorrectAnswers.Any(a => a == i);

                <div class="mb-3 d-flex align-items-center">
                    <label asp-for="@Model.AnswersToTaskList[i].Content">@letter)</label>
                    <input class="form-check-input" type="checkbox" value="@i" name="CorrectAnswers" @(isChecked ? "checked" : "") />
                    <input asp-for="@Model.AnswersToTaskList[i].Content" class="form-control" />
                    <span asp-validation-for="@Model.AnswersToTaskList[i]" class="text-danger"></span>
                </div>

                numberOfCharInASCII++;
            }
        }
        
        <span asp-validation-for="@Model.CorrectAnswers" class="text-danger"></span>
        
    </div>

    <button class="btn btn-primary" type="submit" asp-route-step="3">Poprzedni</button>
    <button asp-page-handler="Step4" class="btn btn-primary" type="submit">Edytuj</button>
</form>