MathWars/Pages/Accounts/ConfirmEmail.cshtml.cs
using MathWars.Entities;
using MathWars.Interfaces;
using MathWars.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace MathWars.Pages.Accounts;

[BindProperties]
public class ConfirmEmailModel : PageModel
{
    private readonly UserManager<ApplicationUser> _userManager;
    private readonly IConfiguration _configuration;
    private readonly IEmailSenderService _emailSenderService;

    public ConfirmEmailModel(UserManager<ApplicationUser> userManager, IConfiguration configuration, IEmailSenderService emailSenderService)
    {
        _userManager = userManager;
        _configuration = configuration;
        _emailSenderService = emailSenderService;
    }

    public string Uid { get; set; }
    public bool IsResendMail { get; set; } = false;

    public async Task<IActionResult> OnGet(string uid)
    {
        var currentUser = await _userManager.GetUserAsync(User);

        if (currentUser != null)
        {
            return RedirectToPage("/Index");
        }

        Uid = uid;
        return Page();
    }

    public async Task<IActionResult> OnPostAsync() 
    {
        var user = await _userManager.FindByIdAsync(Uid);

        if (user != null)
        {
            if(user.EmailConfirmed)
            {
                return RedirectToPage("/Index");
            }

            var token = await _userManager.GenerateEmailConfirmationTokenAsync(user);
            if (!string.IsNullOrEmpty(token))
            {
                await SendEmailConfirmationEmailAsync(user, token);
                IsResendMail = true;
                return Page();
            }
        }

        return Page();
    }
    private async Task SendEmailConfirmationEmailAsync(ApplicationUser user, string token)
    {
        string appDomain = _configuration.GetSection("ApplicationDetails:AppDomain").Value;
        string confirmationLink = _configuration.GetSection("ApplicationDetails:EmailConfirmation").Value;
        UserEmailOptions options = new UserEmailOptions()
        {
            ToEmails = new List<string>() { user.Email },
            PlaceHolders = new List<KeyValuePair<string, string>>
            {
                new KeyValuePair<string, string>("{{UserName}}", user.UserName),
                new KeyValuePair<string, string>("{{Link}}", string.Format(appDomain + confirmationLink,user.Id,token))
            }
        };

        await _emailSenderService.SendEmailForEmailConfirmation(options);
    }

}

MathWars/Pages/Accounts/ConfirmedEmail.cshtml.cs
using MathWars.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MathWars.Pages.Accounts;
public class ConfirmedEmailModel : PageModel
{
    private readonly UserManager<ApplicationUser> _userManager;
    private readonly SignInManager<ApplicationUser> _signInManager;
    public ConfirmedEmailModel(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager)
    {
        _signInManager = signInManager;
        _userManager = userManager;
    }

    public bool Success { get; set; } = false;

    public async Task<IActionResult> OnGet(string uid, string token)
    {
        if(!string.IsNullOrEmpty(uid) && !string.IsNullOrEmpty(token))
        {
            token = token.Replace(" ","+");
            var result = await ConfirmEmailAsync(uid, token);

            if(result.Succeeded)
            {
                var user = await _userManager.FindByIdAsync(uid);
                if (user != null)
                {
                    await _signInManager.SignInAsync(user, isPersistent: false);
                    Success = true;
                    return Page();
                }
            }
        }
        Success = false;

        return Page();
    }

    private async Task<IdentityResult> ConfirmEmailAsync(string uid, string token)
    {
        return await _userManager.ConfirmEmailAsync(await _userManager.FindByIdAsync(uid), token);
    }
}

MathWars/Pages/Accounts/Logout.cshtml.cs
using MathWars.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MathWars.Pages.Accounts
{
    public class LogoutModel : PageModel
    {
        private readonly SignInManager<ApplicationUser> signInManager;

        public LogoutModel(SignInManager<ApplicationUser> signInManager) 
        {
            this.signInManager = signInManager;
        }
        public void OnGet()
        {

        }

        public async Task<IActionResult> OnPostLogoutAsync()
        {
            await signInManager.SignOutAsync();
            return RedirectToPage("/IndexGuest");
        }

        public IActionResult OnPostDontLogoutAsync()
        {
            return RedirectToPage("/Index");
        }
    }
}

MathWars/Pages/Accounts/Profile/AnswerView.cshtml.cs
using MathWars.Entities;
using MathWars.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MathWars.Pages.Accounts.Profile
{
    [Authorize]
    [BindProperties]
    public class AnswerViewModel : PageModel
    {
        private readonly IUnitOfWork _uow;

        public AnswerViewModel(IUnitOfWork uow) 
        {
            _uow = uow;
        }

        public UserAnswer Answer { get; set; }
        public string Uid { get; set; }


        public async Task<IActionResult> OnGetAsync(int id)
        {
            Answer = await _uow.UserAnswersRepository.GetUserAnswersAndTaskAsync(id);

			if (Answer == null)
            {
                return NotFound();
            }

            Uid = Answer.UserId;

            return Page();  
        }
    }
}

MathWars/Pages/Accounts/Profile/IndexProfile.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations;
using MathWars.Helpers;
using MathWars.Entities;
using MathWars.Interfaces;
using MathWars.Models;
using MathWars.Services;

namespace MathWars.Pages
{
    [Authorize]
    [ValidateAntiForgeryToken]
    [BindProperties]
	public class IndexProfileModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly IUnitOfWork _uow;
        private readonly UserManager<ApplicationUser> _userManager;
		private readonly IConfiguration _configuration;
        private readonly IPhotoService _photoService;

        public IndexProfileModel(ILogger<IndexModel> logger, IUnitOfWork uow, 
            UserManager<ApplicationUser> userManager, IConfiguration configuration, 
            IPhotoService photoService)
        {
            _logger = logger;
            _uow = uow;
            _userManager = userManager;
            _configuration = configuration;
            _photoService = photoService;
        }

        public ApplicationUser CurrentUser { get; set; }
		public PaginatedList<UserProfileAnswerModel> AnswersList { get; set; }
        [Required(ErrorMessage = "Jeżeli chcesz zmienić zdjęcie to musisz je dodać"),
            Display(Name = "Dodaj zdjęcie: ")]
        public IFormFile ImageFile { get; set; }
        public string Uid {  get; set; }

        public async Task<IActionResult> OnGet(int? pageIndex, string uid) 
        {
            Uid = uid;
            CurrentUser = await _userManager.FindByIdAsync(uid) ?? new ApplicationUser();

            if (CurrentUser == null) return NotFound();

			int pageSize = _configuration.GetSection("NumberOfElementsInList").GetValue<int>("Profil");

            AnswersList = await _uow.UserAnswersRepository.GetUserProfileAnswersAsync(pageSize, pageIndex, uid);
            return Page();
		}

        public async Task<IActionResult> OnPostUploadImageAsync()
        {
            if (ModelState.IsValid)
            {
                CurrentUser = await _userManager.FindByIdAsync(Uid);

                if (CurrentUser == null) return NotFound();

                var photoResult = await _photoService.AddPhotoAsync(ImageFile, ImageDirectoriesCloudinary.Profiles);

                if (photoResult.Error != null) return Page();

                CurrentUser.ProfileImageUrl = photoResult.SecureUrl.AbsoluteUri;
                CurrentUser.PublicProfileImageId = photoResult.PublicId;

                var result = await _userManager.UpdateAsync(CurrentUser);

                if (result.Succeeded)
                {
                    return RedirectToPage("IndexProfile", new {uid = CurrentUser.Id});
                }
                else
                {
                    return NotFound();
                }
            }

            return RedirectToPage();
        }
    }
}

MathWars/Pages/Accounts/Profile/Leaderboard.cshtml.cs
using MathWars.Entities;
using MathWars.Helpers;
using MathWars.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MathWars.Pages.Accounts.Profile
{
    [Authorize]
    public class LeaderboardModel : PageModel
    {
        private readonly IUnitOfWork _uow;
		private readonly ILogger<IndexModel> _logger;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IConfiguration _configuration;

        public LeaderboardModel(IUnitOfWork uow, ILogger<IndexModel> logger, 
            UserManager<ApplicationUser> userManager, IConfiguration configuration)
        {
            _uow = uow;
            _logger = logger;
            _userManager = userManager;
            _configuration = configuration;
        }

        public PaginatedList<ApplicationUser> Users { get; set; }

        public async Task OnGetAsync(int? pageIndex)
        {
            int pageSize = _configuration.GetSection("NumberOfElementsInList")
                .GetValue<int>("Leaderboard");

            IList<ApplicationUser> usersInRole = await _userManager.GetUsersInRoleAsync("user");

            Users = _uow.UserRepository.GetLeaderboardUsers(usersInRole, pageIndex, pageSize);

        }



    }
}

MathWars/Pages/Accounts/Profile/UserAnswers.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MathWars.Data;
using MathWars.Models;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MathWars.Pages
{
    [Authorize]
    public class UserAnswersModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly ApplicationDbContext _db;
        private readonly UserManager<ApplicationUser> _userManager;
		[BindProperty]
		public ApplicationUser currentUser { get; set; }
		[BindProperty]
		public IEnumerable<Answers> answers { get; set; }

        public UserAnswersModel(ApplicationDbContext db, ILogger<IndexModel> logger, UserManager<ApplicationUser> userManager)
        {
            _db = db;
            _logger = logger;
            _userManager = userManager;
        }

        public async Task OnGet()
        {
            currentUser = await _userManager.GetUserAsync(User);
			answers = _db.Answers.Include(a => a.Task).Where(a => a.UserId == currentUser.Id).ToList();
		}
    }
}

MathWars/Pages/Accounts/Roles/CreateRole.cshtml.cs
using MathWars.Data;
using MathWars.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;

namespace MathWars.Pages.TaskPages;
[Authorize(Policy = "RequireAdminRole")]
[BindProperties]
public class CreateRoleModel : PageModel
{
    private readonly RoleManager<IdentityRole> _roleManager;
    public IdentityRole role { get; set; }
    public CreateRoleModel(RoleManager<IdentityRole> roleManager)
    {
        _roleManager = roleManager;
    }
    public void OnGet()
    {
    }

    public async Task<IActionResult> OnPost()
    {
        if (ModelState.IsValid)
        {
            var result =  await _roleManager.CreateAsync(role);
            if (result.Succeeded)
            {
                return RedirectToPage("ViewRole");
            }
            foreach (IdentityError error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }
        }
        return Page();
    }
}

MathWars/Pages/Accounts/Roles/DeleteRole.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MathWars.Pages.TaskPages;
[Authorize(Policy = "RequireAdminRole")]
[BindProperties]
public class DeleteRoleModel : PageModel
{
    private readonly RoleManager<IdentityRole> _roleManager;
    public IdentityRole role { get; set; }

    public DeleteRoleModel(RoleManager<IdentityRole> roleManager)
    {
        _roleManager = roleManager;
    }
    public async void OnGet(string id)
    {
        role = await _roleManager.FindByIdAsync(id);
    }

    public async Task<IActionResult> OnPost()
    {
        var roleToDelete = await _roleManager.FindByIdAsync(role.Id);

        if (roleToDelete != null)
        {
            var bannedToDeleteList = new List<string> { "admin", "taskManager", "user" };

            foreach (var banned in bannedToDeleteList)
            {
                if (roleToDelete.Name == banned)
                {
                    ModelState.AddModelError("", "You can't delete this role");
                    return Page();
                }
            }

            var result = await _roleManager.DeleteAsync(roleToDelete);

            if (result.Succeeded)
            {
                return RedirectToPage("ViewRole");
            }
            foreach (IdentityError error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }
        }
        return Page();

    }
}

MathWars/Pages/Accounts/Roles/EditRole.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MathWars.Pages.TaskPages;
[Authorize(Policy = "RequireAdminRole")]
[BindProperties]
public class EditRoleModel : PageModel
{
    private readonly RoleManager<IdentityRole> _roleManager;
    public IdentityRole role { get; set; }

    public EditRoleModel(RoleManager<IdentityRole> roleManager)
    {
        _roleManager = roleManager;
    }
    public async void OnGet(string id)
    {
        role = await _roleManager.FindByIdAsync(id);
    }

    public async Task<IActionResult> OnPost()
    {
        var roleToUpdate = await _roleManager.FindByIdAsync(role.Id);

        if (roleToUpdate != null)
        {
            var bannedToUpdateList = new List<string> { "admin", "taskManager", "user" };

            foreach (var banned in bannedToUpdateList)
            {
                if (roleToUpdate.Name == banned)
                {
                    ModelState.AddModelError("", "You can't update this role");
                    return Page();
                }
            }
            roleToUpdate.Name = role.Name;

            var result = await _roleManager.UpdateAsync(roleToUpdate);

            if (result.Succeeded)
            {
                return RedirectToPage("ViewRole");
            }
            foreach (IdentityError error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }
        }
        return Page();
    }
}

MathWars/Pages/Accounts/Roles/ViewRole.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MathWars.Data;
using MathWars.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Configuration;
using MathWars.Helpers;

namespace MathWars.Pages.TaskPages;
[Authorize(Policy = "RequireAdminOrManagerRole")]
public class ViewRoleModel : PageModel
{
    private readonly RoleManager<IdentityRole> _roleManager;
	private readonly IConfiguration _configuration;

	public ViewRoleModel(RoleManager<IdentityRole> roleManager, IConfiguration configuration)
	{
		_roleManager = roleManager;
		_configuration = configuration;
	}

	public PaginatedList<IdentityRole> Roles { get; set; }

	public async Task OnGetAsync(int? pageIndex)
	{
		int pageSize = _configuration.GetSection("NumberOfElementsInList").GetValue<int>("Roles");
		IQueryable<IdentityRole> roleQuery = _roleManager.Roles;

		Roles = await PaginatedList<IdentityRole>.CreateAsync(roleQuery, pageIndex ?? 1, pageSize);
	}
}

MathWars/Pages/Accounts/ConfirmEmail.cshtml
@page
@model MathWars.Pages.Accounts.ConfirmEmailModel
@{
}
<div class="container">
    <div class="container">
        <div class="border p-3 mt-4">
            <div class="row pb-2">
                @if (Model.IsResendMail)
                {
                    <h1>Wysłaliśmy maila ponownie</h1>
                    <h4>Teraz wejdź na swoją pocztę i odbierz maila od nas</h4>
                }
                else
                {
                    <h1>Udało ci się pomyślnie zarejestrować</h1>
                    <h4>Teraz wejdź na swoją pocztę i odbierz maila od nas</h4>
                }
            </div>
            <form method="post">
                <input asp-for="Uid" hidden />
                <div class="mb-3">
                    Nasz mail nie dotarł lub usunąłeś go przez przypadek ?
                </div>
                <button type="submit" class="btn btn-primary" style="width:150px;">Wyślij ponownie</button>
            </form>
        </div>
    </div>
</div>

MathWars/Pages/Accounts/ConfirmedEmail.cshtml
@page
@model MathWars.Pages.Accounts.ConfirmedEmailModel
@{
}
<div class="container">
    <div class="row pt-4">
        @if (@Model.Success)
        {
            <div class="col-5">
                <h1>Super, potwierdziłeś swojego maila : )</h1>
                <h4>Teraz możesz przejść do strony głównej </h4>
            </div>
            <div class="col-5">
                <a asp-area="" asp-page="/Index" class="btn btn-primary" ><i class="bi bi-house"></i><span>Strona Główna</span></a>
            </div>
        }
        else
        {
            <div class="col-5">
                <h1>Coś poszło nie tak : (</h1>
            </div>
        }

    </div>
</div>

MathWars/Pages/Accounts/ForgotPassword.cshtml
@page
@model MathWars.Pages.Accounts.ForgotPasswordModel
@{
}

<div class="container">
    <div class="row">
        <div class="col-mid-4">
            @if(Model?.IsEmailSent == true)
            {
                <div>
                    Wysłaliśmy ci maila :)
                </div>
            }
            else
            {
                <p>Jeżeli zapomniałeś hasła to wprowadź e-mail, na który się zarejestowałeś</p>
                <form method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <input asp-for="Email" class="form-control"/>
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Wyślij" class="btn btn-primary"/>
                    </div>
                </form>
            }
        </div>
    </div>

</div>

MathWars/Pages/Accounts/ForgotPasswordRestart.cshtml
@page
@model MathWars.Pages.Accounts.ForgotPasswordRestartModel
@{
}
<div class="container">
    <div class="border p-3 mt-4">
        @if (Model.IsSuccess)
        {
            <p>Udało ci się zmienić swoje hasło</p>
            <p>Możesz teraz przejść do strony logowania i się zalogować</p>
        }
        else
        {
            <form method="post">
                <div class="row pb-2">
                    <h2 class="text-primary pl-3">Zmień hasło</h2>
                    <hr />
                </div>
                <div asp-validation-summary="ModelOnly"></div>
                <input asp-for="@Model.UserId" hidden />
                <input asp-for="@Model.Token" hidden />
                <div class="mb-3">
                    <label asp-for="@Model.NewPassword"></label>
                    <input asp-for="@Model.NewPassword" class="form-control" />

                </div>

                <div class="mb-3">
                    <label asp-for="@Model.ConfirmNewPassword"></label>
                    <input asp-for="@Model.ConfirmNewPassword" class="form-control" />

                </div>

                <button type="submit" class="btn btn-primary" style="width:150px;">Potwierdź</button>
            </form>
        }
    </div>
</div>

MathWars/Pages/Accounts/Login.cshtml
@page
@model MathWars.Pages.Accounts.LoginModel
@{


<div class="login-box">
    <form method ="post">
        <h1>Zaloguj</h1>
        <div>
            <label asp-for="loginModel.UserName">Nazwa użytkownika:</label>
            <input type="text" asp-for="loginModel.UserName" placeholder="Nazwa użytkownika" >
            <span asp-validation-for="loginModel.UserName" class="text-danger"></span>
        </div>
        <div>
            <label asp-for="loginModel.Password">Hasło:</label>
            <input type="password" asp-for="loginModel.Password" placeholder="Hasło">
            <span asp-validation-for="loginModel.Password" class="text-danger"></span>
        </div>

        <div>

            <input type="checkbox" asp-for="loginModel.RememberMe">
            <label asp-for="loginModel.RememberMe">Zapamiętaj mnie?</label>
            
        </div>

        <div>
                <a class="fyp" asp-page="ForgotPassword">Zapomniałeś hasło?</a>
        </div>

        <div>
            <input type="submit" value="Zaloguj">
        </div>
        <div>
            <a asp-page="Register">Nie masz jeszcze konta? Przejdź do rejestracji!</a>
        </div>
    </form>
</div>

}

MathWars/Pages/Accounts/Logout.cshtml
@page
@model MathWars.Pages.Accounts.LogoutModel
@{
}

<form method="post">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-sm-12 col-md-12 col-lg-4">
                <p>Czy napewno chcesz się wylogować?</p>
                <p>
                    <button class="btn btn-primary" asp-page-handler="Logout">Tak</button>
                    <button class="btn btn-light m-lg-5 border-dark" asp-page-handler="DontLogout">Nie</button>
                </p>
            </div>
        </div>
    </div>
</form>

MathWars/Pages/Accounts/Register.cshtml
@page
@model MathWars.Pages.Accounts.RegisterModel
@{
}



<div class="register-box">
    <div>
        <div>
            <h1>Rejestracja</h1>
            <form method="post">
                <div>
                    <label>Nazwa użytkownika</label>
                    <input type="text" asp-for="registerModel.UserName" placeholder="Nazwa użytkownika" />
                <span asp-validation-for="registerModel.UserName" class="text-danger"></span>
                </div>
                <div>
                    <label>Adres Email</label>
                    <input type="email" asp-for="registerModel.Email" placeholder="Adres Email" />
                <span asp-validation-for="registerModel.Email" class="text-danger"></span>
                </div>
                <div>
                    <label>Hasło</label>
                    <input type="password" asp-for="registerModel.Password" placeholder="Hasło" />
                    <span asp-validation-for="registerModel.Password" class="text-danger"></span>
                </div>
                <div>
                    <label>Powtórz hasło</label>
                    <input type="password" asp-for="registerModel.ConfirmPassword" placeholder="Powtórz hasło" />
                    <span asp-validation-for="registerModel.ConfirmPassword" class="text-danger"></span>
                </div>
                <div>
                    <input type="submit" value="Rejestruj">
                </div>
            </form>
        </div>
    </div>
</div>